name: Build and publish Docker image

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/telegram-reaction-bot:latest

      - name: Deploy to Koyeb (optional)
        if: ${{ secrets.KOYEB_TOKEN && secrets.KOYEB_SERVICE_ID }}
        run: |
          echo "Deploying to Koyeb..."
          curl -s -X POST "https://app.koyeb.com/api/v1/services/${{ secrets.KOYEB_SERVICE_ID }}/deployments" \
            -H "Authorization: Bearer ${{ secrets.KOYEB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"container": {"image": "ghcr.io/'"${{ github.repository_owner }}"'/telegram-reaction-bot:latest"}}'
